import json
import sys
import types
from pathlib import Path

from risk_model_workbench.cli import main
from risk_model_workbench.data.sql_review import review_sql_text
from risk_model_workbench.feature_refine import main as feature_refine_main
from risk_model_workbench.registry import load_artifact_manifest
from risk_model_workbench.state import create_run_state, load_run_state, save_run_state


def _write_minimal_project(project_dir: Path, run_id: str = "run1") -> Path:
    (project_dir / "configs").mkdir(parents=True)
    (project_dir / "runs" / "feature_prescreen" / "results").mkdir(parents=True)
    (project_dir / "project.yml").write_text(
        "\n".join(
            [
                "project:",
                "  name: pytest-project",
                "  display_name: Pytest Project",
                "  scenario: pytest",
                "data:",
                "  source_table: mart.base",
                "  id_columns: [uid, mdl_dte]",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    (project_dir / "configs" / "feature_select.yaml").write_text(
        "\n".join(
            [
                "feature_select:",
                "  wide_table:",
                "    base_table: mart.base",
                "    output_table: mart.wide",
                "    join_keys: [uid, mdl_dte]",
                "    base_columns: [uid, mdl_dte, final_flag, target]",
                "    base_where: ds is not null",
                "    feature_where: ds is not null",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    (project_dir / "runs" / "feature_prescreen" / "results" / "prescreen_final_remain_features.json").write_text(
        json.dumps({"mart.feature_a": ["feat_a", "feat_b"]}) + "\n",
        encoding="utf-8",
    )
    run_dir = project_dir / "runs" / run_id
    save_run_state(run_dir, create_run_state(project_dir, run_id=run_id, workflow="full_modeling"))
    return run_dir


def _install_fake_tmlsqlclient(monkeypatch, calls: list[str]) -> None:
    class FakeResult:
        def to_pandas(self):
            return None

    class FakeClient:
        def sql(self, sql):
            calls.append(sql)
            return FakeResult()

        def stop(self):
            calls.append("stop")

    tmlpatch = types.ModuleType("tmlpatch")
    database = types.ModuleType("tmlpatch.database")
    database.TMLSQLClient = FakeClient
    monkeypatch.setitem(sys.modules, "tmlpatch", tmlpatch)
    monkeypatch.setitem(sys.modules, "tmlpatch.database", database)


def test_build_wide_sql_execute_requires_sql_approval(tmp_path):
    project_dir = tmp_path / "project"
    run_dir = _write_minimal_project(project_dir)

    code = main(["build-wide-sql", "--project", str(project_dir), "--run-id", "run1", "--execute"])

    assert code == 1
    state = load_run_state(run_dir)
    assert state["stages"]["build_wide_sql"]["status"] == "failed"
    assert state["stages"]["build_wide_sql"]["failure_code"] == "sql_approval_required"


def test_build_wide_sql_execute_registers_artifacts(tmp_path, monkeypatch):
    project_dir = tmp_path / "project"
    run_dir = _write_minimal_project(project_dir)
    calls: list[str] = []
    _install_fake_tmlsqlclient(monkeypatch, calls)

    code = main(
        [
            "build-wide-sql",
            "--project",
            str(project_dir),
            "--run-id",
            "run1",
            "--execute",
            "--sql-approved",
        ]
    )

    assert code == 0
    assert calls[0].startswith("-- Generated by risk_model_workbench.")
    assert "create table if not exists mart.wide as" in calls[0]
    execution_path = run_dir / "feature_selection" / "wide_table_execution.json"
    execution = json.loads(execution_path.read_text(encoding="utf-8"))
    assert execution["status"] == "executed"
    assert execution["approved"] is True
    assert execution["output_table"] == "mart.wide"
    state = load_run_state(run_dir)
    assert state["stages"]["build_wide_sql"]["status"] == "done"
    assert "feature_selection/wide_table_execution.json" in state["stages"]["build_wide_sql"]["artifacts"]
    manifest_paths = {item["path"] for item in load_artifact_manifest(run_dir)["artifacts"]}
    assert "queries/06_build_prescreen_wide_table.sql" in manifest_paths
    assert "feature_selection/wide_sql_summary.json" in manifest_paths
    assert "feature_selection/prescreen_wide_feature_map.csv" in manifest_paths
    assert "feature_selection/wide_table_execution.json" in manifest_paths
    assert "feature_selection/profiles/wide_table_profile.json" in manifest_paths
    assert "queries/sql_evidence_manifest.json" in manifest_paths
    assert not (project_dir / "feature_selection" / "wide_table_execution.json").exists()


def test_build_wide_sql_prefers_runtime_prescreen_paths(tmp_path):
    project_dir = tmp_path / "project"
    run_dir = _write_minimal_project(project_dir)
    runtime_prescreen = run_dir / "feature_selection" / "prescreen" / "results"
    runtime_prescreen.mkdir(parents=True)
    (runtime_prescreen / "prescreen_final_remain_features.json").write_text(
        json.dumps({"mart.feature_runtime": ["feat_runtime"]}) + "\n",
        encoding="utf-8",
    )
    runtime_config_dir = run_dir / "configs_runtime"
    runtime_config_dir.mkdir(parents=True)
    (runtime_config_dir / "feature_select.yaml").write_text(
        "\n".join(
            [
                "feature_select:",
                "  wide_table:",
                "    base_table: mart.base",
                "    output_table: mart.wide",
                "    join_keys: [uid, mdl_dte]",
                "    base_columns: [uid, mdl_dte, final_flag, target]",
                f"    remain_features_path: {runtime_prescreen / 'prescreen_final_remain_features.json'}",
                f"    sql_output: {run_dir / 'queries' / '06_build_prescreen_wide_table.sql'}",
                f"    feature_map_output: {run_dir / 'feature_selection' / 'prescreen_wide_feature_map.csv'}",
                f"    summary_output: {run_dir / 'feature_selection' / 'wide_sql_summary.json'}",
            ]
        )
        + "\n",
        encoding="utf-8",
    )

    code = main(["build-wide-sql", "--project", str(project_dir), "--run-id", "run1"])

    assert code == 0
    sql = (run_dir / "queries" / "06_build_prescreen_wide_table.sql").read_text(encoding="utf-8")
    assert "feat_runtime" in sql
    assert "feat_a" not in sql
    assert not (project_dir / "queries" / "06_build_prescreen_wide_table.sql").exists()


def test_build_wide_sql_rejects_output_escape_before_generator_side_effects(tmp_path, monkeypatch):
    project_dir = tmp_path / "project"
    run_dir = _write_minimal_project(project_dir)
    called = False

    def generator(**_kwargs):
        nonlocal called
        called = True
        raise AssertionError("generator must not run for escaped output")

    import risk_model_workbench.cli as cli_module

    monkeypatch.setattr(cli_module, "generate_wide_sql", generator)
    code = main(
        [
            "build-wide-sql",
            "--project",
            str(project_dir),
            "--run-id",
            "run1",
            "--sql-output",
            "../outside.sql",
        ]
    )

    assert code == 1
    assert called is False
    assert not (project_dir.parent / "outside.sql").exists()
    assert load_run_state(run_dir)["stages"]["build_wide_sql"]["status"] == "failed"


def test_sql_review_gate_blocks_high_risk_even_when_approved(tmp_path, monkeypatch):
    project_dir = tmp_path / "project"
    run_dir = _write_minimal_project(project_dir)

    def fake_generate_wide_sql(**kwargs):
        sql_path = kwargs["sql_output_path"]
        feature_map_path = kwargs["feature_map_path"]
        summary_path = kwargs["summary_path"]
        sql_path.parent.mkdir(parents=True, exist_ok=True)
        feature_map_path.parent.mkdir(parents=True, exist_ok=True)
        summary_path.parent.mkdir(parents=True, exist_ok=True)
        sql_path.write_text("drop table mart.unsafe;\n", encoding="utf-8")
        feature_map_path.write_text("output_feature\nfeat_a\n", encoding="utf-8")
        summary_path.write_text(json.dumps({"output_table": "mart.unsafe"}) + "\n", encoding="utf-8")
        return sql_path, feature_map_path, summary_path

    import risk_model_workbench.cli as cli_module

    monkeypatch.setattr(cli_module, "generate_wide_sql", fake_generate_wide_sql)

    code = main(["build-wide-sql", "--project", str(project_dir), "--run-id", "run1", "--execute", "--sql-approved"])

    assert code == 1
    state = load_run_state(run_dir)
    assert state["stages"]["build_wide_sql"]["status"] == "failed"
    review = json.loads((run_dir / "feature_selection" / "sql_review.json").read_text(encoding="utf-8"))
    assert review["high_risk"] is True
    assert any(item["rule_id"] == "dangerous_statement" for item in review["findings"])


def test_sql_review_safe_and_high_risk_patterns():
    safe = review_sql_text("create table if not exists mart.wide as select t1.uid from (select uid from mart.base) t1;\n", approved_for_execution=True)
    unsafe = review_sql_text("select * from a join b on 1=1;\n", approved_for_execution=True)

    assert safe["risk_level"] == "low"
    assert unsafe["high_risk"] is True
    assert any(item["rule_id"] == "cartesian_join_condition" for item in unsafe["findings"])


def test_feature_prescreen_cli_registers_run_artifacts(tmp_path, monkeypatch):
    project_dir = tmp_path / "project"
    run_dir = _write_minimal_project(project_dir)
    seen: dict = {}

    def fake_prescreen_service(**kwargs):
        seen.update(kwargs)
        results_dir = project_dir / "runs" / "feature_prescreen" / "results"
        results_dir.mkdir(parents=True, exist_ok=True)
        (results_dir / "prescreen_run_summary.json").write_text('{"final_remain": 2}\n', encoding="utf-8")
        (results_dir / "prescreen_final_remain_features.json").write_text('{"mart.feature_a": ["feat_a", "feat_b"]}\n', encoding="utf-8")
        (results_dir / "prescreen_table_summary.csv").write_text("table,final_remain\nmart.feature_a,2\n", encoding="utf-8")
        return 0

    import risk_model_workbench.batch_feature_select as batch_feature_select_module

    monkeypatch.setattr(batch_feature_select_module, "run_prescreen_service", fake_prescreen_service)

    code = main(["feature", "prescreen", "--project", str(project_dir), "--run-id", "run1"])

    assert code == 0
    assert seen["run_dir"] == run_dir
    assert seen["stage"] == "feature_prescreen"
    state = load_run_state(run_dir)
    artifacts = set(state["stages"]["feature_prescreen"]["artifacts"])
    assert "feature_selection/prescreen_run_summary.json" in artifacts
    assert "feature_selection/prescreen_final_remain_features.json" in artifacts
    assert "feature_selection/prescreen_table_summary.csv" in artifacts
    manifest_paths = {item["path"] for item in load_artifact_manifest(run_dir)["artifacts"]}
    assert "feature_selection/prescreen_run_summary.json" in manifest_paths
    assert "feature_selection/prescreen_final_remain_features.json" in manifest_paths
    assert "feature_selection/prescreen_table_summary.csv" in manifest_paths


def test_feature_refine_sample_max_rows_overrides_dry_run_sql(tmp_path):
    project_dir = tmp_path / "project"
    (project_dir / "configs").mkdir(parents=True)
    (project_dir / "feature_map.csv").write_text("output_feature\nuid\nfeat_a\nfeat_b\n", encoding="utf-8")
    (project_dir / "configs" / "refine_features.yaml").write_text(
        "\n".join(
            [
                "feature_refine:",
                "  input:",
                "    wide_table: mart.wide",
                "    feature_map: feature_map.csv",
                "    label_column: target",
                "    split_column: final_flag",
                "    train_value: DEV",
                "    valid_value: OOT",
                "    id_columns: [uid]",
                "    base_columns: [uid, target, final_flag]",
                "  sampling:",
                "    where: final_flag in ('DEV','OOT')",
                "    max_rows: 10",
                "  dp_feather:",
                "    dataset_id: refine_sample",
                "  output_dir: runs/refine",
                "  random_seed: 0",
            ]
        )
        + "\n",
        encoding="utf-8",
    )

    code = feature_refine_main(
        [
            "--project-dir",
            str(project_dir),
            "--config",
            "configs/refine_features.yaml",
            "--dry-run-sql",
            "--sample-max-rows",
            "123",
        ]
    )

    assert code == 0
    metadata = json.loads((project_dir / "data" / "profile" / "dp_feather_datasets" / "refine_sample.json").read_text())
    assert "limit 123" in metadata["sql"]
    assert "limit 10" not in metadata["sql"]


def test_feature_refine_local_feather_dry_run_writes_profile_without_sql(tmp_path):
    import pandas as pd

    project_dir = tmp_path / "project"
    (project_dir / "configs").mkdir(parents=True)
    local_path = project_dir / "data" / "raw" / "model.feather"
    local_path.parent.mkdir(parents=True)
    pd.DataFrame(
        {
            "uid": [1, 2, 3, 4],
            "target": [0, 1, 0, 1],
            "final_flag": ["DEV", "DEV", "OOT", "OOT"],
            "feat_a": [0.1, 0.2, 0.3, 0.4],
            "feat_b": [1, 2, 3, 4],
        }
    ).to_feather(local_path)
    (project_dir / "configs" / "refine_features.yaml").write_text(
        "\n".join(
            [
                "feature_refine:",
                "  input:",
                "    local_feather_path: data/raw/model.feather",
                "    label_column: target",
                "    split_column: final_flag",
                "    train_value: DEV",
                "    valid_value: OOT",
                "    id_columns: [uid]",
                "    base_columns: [uid, target, final_flag]",
                "  output_dir: runs/refine",
                "  dp_feather:",
                "    dataset_id: local_refine_sample",
                "  preprocessing: {}",
            ]
        )
        + "\n",
        encoding="utf-8",
    )

    code = feature_refine_main(
        [
            "--project-dir",
            str(project_dir),
            "--config",
            "configs/refine_features.yaml",
            "--dry-run-sql",
        ]
    )

    assert code == 0
    metadata = json.loads((project_dir / "data" / "profile" / "dp_feather_datasets" / "local_refine_sample.json").read_text())
    assert metadata["source"] == "local_feather"
    assert metadata["sql"] == ""
    profile = json.loads((project_dir / "runs" / "refine" / "local_feather_profile.json").read_text(encoding="utf-8"))
    assert profile["candidate_feature_count"] == 2


def test_feature_refine_cli_registers_run_feature_outputs(tmp_path, monkeypatch):
    project_dir = tmp_path / "project"
    run_dir = project_dir / "runs" / "run1"
    (project_dir / "configs").mkdir(parents=True)
    output_dir = project_dir / "runs" / "refine"
    output_dir.mkdir(parents=True)
    (project_dir / "configs" / "refine_features.yaml").write_text(
        "\n".join(["feature_refine:", "  output_dir: runs/refine"]) + "\n",
        encoding="utf-8",
    )
    (output_dir / "stage_summary.json").write_text('{"final_features": 2}\n', encoding="utf-8")
    (output_dir / "resource_usage.json").write_text('{"observed_peak_multiplier": 2.1}\n', encoding="utf-8")
    (output_dir / "final_500_features.txt").write_text("feat_a\nfeat_b\n", encoding="utf-8")
    (output_dir / "final_features.txt").write_text("feat_a\nfeat_b\n", encoding="utf-8")
    save_run_state(run_dir, create_run_state(project_dir, run_id="run1", workflow="full_modeling"))
    seen: dict = {}

    def fake_refine_service(**kwargs):
        seen.update(kwargs)
        return 0

    import risk_model_workbench.feature_refine as feature_refine_module

    monkeypatch.setattr(feature_refine_module, "run_refine_service", fake_refine_service)

    code = main(
        [
            "feature",
            "refine",
            "--project",
            str(project_dir),
            "--run-id",
            "run1",
            "--config",
            "configs/refine_features.yaml",
            "--sample-max-rows",
            "321",
        ]
    )

    assert code == 0
    assert seen["sample_max_rows"] == 321
    assert seen["run_dir"] == run_dir
    state = load_run_state(run_dir)
    artifacts = set(state["stages"]["feature_refine"]["artifacts"])
    assert "feature_selection/stage_summary.json" in artifacts
    assert "feature_selection/feature_stage_summary.json" in artifacts
    assert "feature_selection/resource_usage.json" in artifacts
    assert "feature_selection/final_500_features.txt" in artifacts
    assert "feature_selection/final_features.txt" in artifacts


def test_feature_refine_cli_marks_stage_failed_on_invalid_sample_max_rows(tmp_path):
    project_dir = tmp_path / "project"
    run_dir = project_dir / "runs" / "run1"
    (project_dir / "configs").mkdir(parents=True)
    (project_dir / "configs" / "refine_features.yaml").write_text(
        "\n".join(["feature_refine:", "  output_dir: runs/refine"]) + "\n",
        encoding="utf-8",
    )
    save_run_state(run_dir, create_run_state(project_dir, run_id="run1", workflow="full_modeling"))

    code = main(
        [
            "feature",
            "refine",
            "--project",
            str(project_dir),
            "--run-id",
            "run1",
            "--config",
            "configs/refine_features.yaml",
            "--sample-max-rows",
            "0",
        ]
    )

    assert code == 1
    state = load_run_state(run_dir)
    assert state["stages"]["feature_refine"]["status"] == "failed"
    assert state["stages"]["feature_refine"]["failure_code"] == "data_missing"
